global using Delta.Polling.Both.Common.Exceptions;
global using Delta.Polling.Both.Common.Responses;
global using Delta.Polling.Both.Common.Statics;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using RestSharp;
